pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    } 
    stage('Run the Container') {
      steps{
        echo 'Running the container'
        sh 'docker run -d --name con1 -p 8080:80 nginx'
      }
    }
  }
}
